### ISSUE TITLE
Add searching?

### ISSUE THREAD

**Issue by nessusing** [ai-eks/OpenClubhouse#1]
Awesome project! Possible to add search functionality for rooms in the near future?

**Comment by leiyiz** [comment]
there is no search ability for the original clubhouse so not sure if it is possible

**Comment by nessusing** [comment]
Thanks! Yeah I am new to CH, didn't know search was yet to come.
Your project kicks ass! I have it up and running on my PC now! Saves me the money to buy an iOS device, lol!

**Comment by leiyiz** [comment]
not my project lol it's @ai-eks I just saw your issue and thought about commenting

**Comment by ai-eks** [comment]
@leiyiz Thank you for your explaination.
