### ISSUE TITLE
CAN_NOT_GET_GATEWAY_SERVER

### ISSUE THREAD

**Issue by luckycat0426** [ai-eks/OpenClubhouse#13]
Can't play Audio
{ "name": "AgoraRTCException", "code": "CAN_NOT_GET_GATEWAY_SERVER", "message": "AgoraRTCError CAN_NOT_GET_GATEWAY_SERVER: no active status", "data": { "retry": false } }

**Comment by ai-eks** [comment]
The [AgoraWebSDK-NG/api](https://agoraio-community.github.io/AgoraWebSDK-NG/api/en/) says "Fails to get the IP addresses of the Agora servers." for this error code. It seems like a network or transient issue.
Since my account was blocked, I won't investigate SDK issues any more.

**Comment by luckycat0426** [comment]
> The [AgoraWebSDK-NG/api](https://agoraio-community.github.io/AgoraWebSDK-NG/api/en/) says "Fails to get the IP addresses of the Agora servers." for this error code. It seems like a network or transient issue.
> Since my account was blocked, I won't investigate SDK issues any more.

https://github.com/callmearta/clubhouse-desktop/tree/150ba375cdb917651c57b993b851aaf501f9fd75

>  Also i'm using a really old version of Agora web SDK and that's because new version of Agora won't work because of the limitation they put on the user agents for clubhouse ( at least i think so ).

Someone says the newest SDK has limitation. I will try to replace your SDK with old one .
I can Email you a Google Voice  with a registered clubhouse account if you need it.

**Comment by ai-eks** [comment]
Hope you solve the problem.
I am not interested in it anymore. Thanks anyway.
