### ISSUE TITLE
Has the speak part been reverse engineered?

### ISSUE THREAD

**Issue by nessusing** [ai-eks/OpenClubhouse#4]
So now with everything setup and working, I wonder if speak will be supported?

I see that AgoraRTC is used for streaming. I am not a web developer, not sure if up-streaming (speak) is possible?

**Comment by ai-eks** [comment]
The Agora SDK also supports the up-streaming, also it needs to do some interactions with the Clubhouse server. You can get more info from other repos like https://github.com/zhuowei/hipster.house, https://github.com/stypr/clubhouse-py or https://github.com/grishka/Houseclub.
