### ISSUE TITLE
Any Tutorial on how to run the code.. having difficulties to run it on my windows

### ISSUE THREAD

**Issue by WeAreGrowthHackers** [ai-eks/OpenClubhouse#8]
Any Tutorial on how to run the code.. having difficulties to run it on my windows? Thanks

**Comment by ai-eks** [comment]
If you run it on windows, you should change the environment variable setting commands in run.sh to accord with the terminal you use (cmd or powershell). Then, just run all these commands in terminal directly.

Anyway, using this repo will increase the risk of ban. I recommend that invited users can use other third-party client to use Clubhouse. You can find several repos on GitHub by searching Clubhouse.

**Comment by enesinan** [comment]
why using this repo will increase the risk of ban

**Comment by ai-eks** [comment]
> why using this repo will increase the risk of ban

I mean the whole project especially the worker.
Joining too many rooms is not welcome by some people.

**Comment by ai-eks** [comment]
Close issue duo to no more feedbacks.

**Comment by Bastien-Virmaux** [comment]
i am new to github.

**Comment by enes-dev** [comment]
> If you run it on windows, you should change the environment variable setting commands in run.sh to accord with the terminal you use (cmd or powershell). Then, just run all these commands in terminal directly.
> 
> Anyway, using this repo will increase the risk of ban. I recommend that invited users can use other third-party client to use Clubhouse. You can find several repos on GitHub by searching Clubhouse.

    https://youtu.be/RGOj5yH7evk

**Comment by enesinan** [comment]
https://youtu.be/RGOj5yH7evk
